file(MAKE_DIRECTORY "${EVIDENCE}")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef RUN)
set(RECORDING "${EVIDENCE}/black-silent-${RUN}.mkv")
execute_process(COMMAND "${HOST}" "${RUNTIME}" "${RECORDING}" RESULT_VARIABLE STATUS TIMEOUT 15)
if(NOT STATUS EQUAL 0)
  message(FATAL_ERROR "Native recording validation failed (${STATUS})")
endif()
execute_process(COMMAND "${FFMPEG}" -hide_banner -v error -xerror -i "${RECORDING}" -map 0:v:0 -map 0:a:0 -f null - RESULT_VARIABLE DECODE TIMEOUT 15 OUTPUT_QUIET ERROR_VARIABLE ERROR)
if(NOT DECODE EQUAL 0)
  message(FATAL_ERROR "Finalized MKV did not decode both audio and video (${DECODE}): ${ERROR}")
endif()
file(WRITE "${EVIDENCE}/latest-recording.txt" "${RECORDING}\n")
message(STATUS "Both H264/AAC tracks decoded from completed black/silent proof MKV")
